### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by kwoshvick** [Aztec-Sytems/neiley#11]
* Link the product with the quantity available
* Alert admin when stock level are past a certain number
* Perform a basic stock taking

**Comment by Kimkykie** [comment]
![alert](https://user-images.githubusercontent.com/16070564/62227365-72a6b280-b3c4-11e9-8104-04b670026329.png)
Currently alert will show on table if it is below minimum alert quantity.
Email sending when stock is below limit will come later as discussed.
